name: Build Desktop app

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build Desktop app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Display Java version
        run: java -version

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew composeApp:createDistributable

      - name: Decode signing key
        run: |
          echo "${{ secrets.SIGNING_KEY }}" | base64 --decode > signing-key.p12

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v16.0
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        with:
          command: make copied-site
          agree_to_license: 1

