name: Build & Release Desktop App

on:
  push:
    tags:
      - '*'   # Run on any tag push, e.g. v1.0.0

permissions:
  contents: write   # Required for GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Build distributables with Gradle
        run: |
          chmod +x gradlew
          ./gradlew composeApp:createDistributable

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v19.0
        env:
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          agree_to_license: 1
