name: Build Desktop app

on:
  push:
    tags:
      - '*'

permissions:
  contents: write

jobs:
  build:
    name: Build Desktop app
    runs-on: ubuntu-latest
    steps:
      - name: Checkout workspace
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Display Java version
        run: java -version

      - name: Build with Gradle
        run: |
          chmod +x gradlew
          ./gradlew composeApp:createDistributable

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v18.1
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
          SIGNING_KEY: ${{ secrets.SIGNING_KEY }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        with:
          command: make copied-site
          signing_key: ${{ secrets.SIGNING_KEY }}
          signing_key_password: ${{ secrets.SIGNING_KEY_PASSWORD }}
          extra_flags: -f ci.conveyor.conf
          agree_to_license: 1

