name: Build & Release Desktop App

on:
  push:
    tags:
      - '*'   # Run on any tag push, e.g. v1.0.0

permissions:
  contents: write   # Required for GitHub Releases

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Verify Java version
        run: java -version

      - name: Extract version from tag
        run: |
          VERSION_NAME="${GITHUB_REF#refs/tags/}"  # Remove "refs/tags/"
          echo "Extracted VERSION_NAME: $VERSION_NAME"  # Debugging step
          echo "VERSION_NAME=$VERSION_NAME" >> $GITHUB_ENV

      - name: Update version in gradle.properties
        run: |
          sed -i "s/^version=.*/version=${{ env.VERSION_NAME }}/" gradle.properties

      - name: Commit and push version change to main branch
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git fetch origin main
          git checkout main
          git pull origin main

          git add gradle.properties
          git commit -m "Bump version to ${{ env.VERSION_NAME }}" || echo "No changes to commit"
          git push origin main
        env:
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}

      - name: Build distributables with Gradle
        run: |
          chmod +x gradlew
          ./gradlew composeApp:createDistributable

      - name: Run Conveyor
        uses: hydraulic-software/conveyor/actions/build@v19.0
        env:
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          MY_GITHUB_TOKEN: ${{ secrets.MY_GITHUB_TOKEN }}
        with:
          command: make copied-site
          extra_flags: -f ci.conveyor.conf
          signing_key: ${{ secrets.SIGNING_KEY }}
          agree_to_license: 1
          cache_key: conveyor
          cache_path: .conveyor

